version: '2'

services:
  web:
    image: nginx:1.16.0-alpine
    volumes:
      - "./docker/default.conf:/etc/nginx/conf.d/default.conf"
      - "./data/logs-nginx:/var/log/nginx"
      - "./:/var/www/html"
    ports:
      - "80:80"

  php:
    build: "."
    volumes:
      - "./docker/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"

  db:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sistema
      POSTGRES_DB: sistema
      POSTGRES_PASSWORD: sistema
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:4.11
    environment:
      PGADMIN_DEFAULT_EMAIL: "danilo.souza@edu.unipar.br"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "8080:80"
    volumes:
      - "./data/pgadmin-data:/var/lib/pgadmin"

